# Generated by Django 4.1.5 on 2023-04-24 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_cnt', models.IntegerField(default=1)),
                ('warehouse_id', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PACKING', 'packing'), ('PACKED', 'packed'), ('LOADING', 'loading'), ('LOADED', 'loaded'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered')], default='packing', max_length=50)),
                ('addr_x', models.IntegerField(default=5)),
                ('addr_y', models.IntegerField(default=5)),
                ('ups_id', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.product')),
            ],
        ),
    ]
