# Generated by Django 4.1.5 on 2023-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ordered'), ('PACKING', 'packing'), ('PACKED', 'packed'), ('LOADING', 'loading'), ('LOADED', 'loaded'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered')], default='ordered', max_length=50),
        ),
    ]
